/**
 * Domain schema.
 *
 * The invariants encoded here are documented in CLAUDE.md and justified in
 * docs/decisions.md. The load-bearing ones:
 *
 *   - `institutionId` on every campus-scoped table (expansion is campus-by-campus)
 *   - `course` is durable; codes live in `courseCodeAlias` with term validity
 *   - `(tutor, course)` is the core relationship, not `tutor`
 *   - a user can be both tutor and student
 *   - money is integer minor units
 *   - reliability is timestamped facts only
 */

import {
  pgTable,
  pgEnum,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  date,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { user, session, account, verification } from "./auth-schema";

/* -------------------------------------------------------------------------- */
/* enums                                                                      */
/* -------------------------------------------------------------------------- */

export const kycStatus = pgEnum("kyc_status", [
  "not_started", // deferred until first accepted request — see decisions.md
  "pending",
  "verified",
  "restricted",
]);

export const tutorCourseStatus = pgEnum("tutor_course_status", [
  "pending_verification",
  "active",
  "winding_down", // graduating: no new engagements, existing ones run out
  "retired",
]);

export const matchRequestStatus = pgEnum("match_request_status", [
  "pending",
  "accepted",
  "declined", // explicit pass — never penalised
  "expired", // silent expiry — carries a ranking penalty
  "withdrawn", // another tutor accepted first
]);

export const engagementStatus = pgEnum("engagement_status", [
  "active",
  "completed",
  "refunded",
  "cancelled",
]);

export const sessionStatus = pgEnum("session_status", [
  "scheduled",
  "completed",
  "cancelled",
  "disputed",
]);

/** How a session's attendance was settled. Mutual confirm is adversarial — the
 *  tutor is paid if attended, the student gets the session back if not. */
export const attendanceResolution = pgEnum("attendance_resolution", [
  "both_confirmed",
  "auto_released", // confirmation window lapsed, defaulted to attended
  "disputed",
  "resolved_attended",
  "resolved_not_attended",
]);

/** Timestamped facts only. Nothing subjective, nothing that proxies for ability. */
export const reliabilityEventType = pgEnum("reliability_event_type", [
  "attended",
  "late_cancelled",
  "no_showed",
  "payment_failed",
]);

export const ledgerEntryType = pgEnum("ledger_entry_type", [
  "package_purchase", // deferred revenue on receipt, not income
  "session_earned", // recognised as a session is delivered
  "tutor_payout",
  "platform_fee",
  "refund",
  "guarantee_absorbed", // platform eats tutor pay on a first-session refund
]);

export const packageKind = pgEnum("package_kind", [
  "exam_anchored", // default: ~4 sessions to the next exam
  "through_final", // discounted upsell
  // One session, full price, renewal only. It exists for the tail of the term,
  // where a package would sell sessions the term has no room for. Never
  // offered at a first purchase — see billing/pricing.ts for why a cold
  // one-off and a top-up are different products.
  "top_up",
]);

/* -------------------------------------------------------------------------- */
/* institution + identity                                                     */
/* -------------------------------------------------------------------------- */

export const institution = pgTable("institution", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  emailDomain: text("email_domain").notNull(), // gates .edu verification
  timezone: text("timezone").notNull(), // IANA
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Identity only. Better Auth owns this table's shape — see `src/server/auth.ts`
 * and the auth tables in `./auth-schema.ts`.
 *
 * Deliberately thin: no domain columns live here. `institutionId` is the tenant
 * key and stays on the profile tables, not inside a dependency-owned table, so a
 * Better Auth upgrade cannot touch it. Under magic link, Better Auth's
 * `emailVerified` IS the .edu verification — the link goes to the .edu address —
 * so there is no separate verification flag to keep in sync.
 *
 * These are generated by `npx @better-auth/cli generate` — edit `auth-schema.ts`
 * only through that command, never by hand.
 *
 * Note the booking table is exported as `sessionBooking`, not `session`. The
 * Better Auth adapter resolves its models by schema key, so a `session` export
 * of ours silently bound its session model to the wrong table.
 */
export { user, session, account, verification };

/**
 * Profiles are split from `user` because on a peer campus the same person is
 * routinely both tutor and student, and their histories must not mix.
 * `userId` is NOT NULL — there is no parent-managed account in this product.
 */
export const studentProfile = pgTable(
  "student_profile",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    institutionId: uuid("institution_id")
      .notNull()
      .references(() => institution.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("student_profile_user_idx").on(t.userId)],
);

export const tutorProfile = pgTable(
  "tutor_profile",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    institutionId: uuid("institution_id")
      .notNull()
      .references(() => institution.id),

    headline: text("headline"),
    bio: text("bio"),

    stripeAccountId: text("stripe_account_id"),
    kycStatus: kycStatus("kyc_status").notNull().default("not_started"),

    expectedGraduationOn: date("expected_graduation_on"), // drives wind-down
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("tutor_profile_user_idx").on(t.userId)],
);

/* -------------------------------------------------------------------------- */
/* catalog                                                                    */
/* -------------------------------------------------------------------------- */

export const term = pgTable(
  "term",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    institutionId: uuid("institution_id")
      .notNull()
      .references(() => institution.id),
    name: text("name").notNull(), // "Fall 2026"
    startsOn: date("starts_on").notNull(),
    endsOn: date("ends_on").notNull(),
  },
  (t) => [uniqueIndex("term_institution_name_idx").on(t.institutionId, t.name)],
);

/** First-class, not a profile detail: an instructor change invalidates the wedge. */
export const professor = pgTable(
  "professor",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    institutionId: uuid("institution_id")
      .notNull()
      .references(() => institution.id),
    name: text("name").notNull(),
    department: text("department"),
  },
  (t) => [index("professor_institution_idx").on(t.institutionId)],
);

/**
 * The durable course. Quality scores and tutor history attach HERE — never to a
 * code string or an offering — so a renumbering does not fork a tutor's record.
 */
export const course = pgTable(
  "course",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    institutionId: uuid("institution_id")
      .notNull()
      .references(() => institution.id),
    title: text("title").notNull(), // "Calculus I"
    department: text("department").notNull(),
    /** Seeded weed-out courses launch first; the full catalog is vanity work. */
    isSeeded: boolean("is_seeded").notNull().default(false),
  },
  (t) => [index("course_institution_idx").on(t.institutionId)],
);

/** Course codes get renumbered between terms. Never key on the string. */
export const courseCodeAlias = pgTable(
  "course_code_alias",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    courseId: uuid("course_id")
      .notNull()
      .references(() => course.id),
    code: text("code").notNull(), // "MATH 125"
    validFromTermId: uuid("valid_from_term_id").references(() => term.id),
    validToTermId: uuid("valid_to_term_id").references(() => term.id), // null = current
  },
  (t) => [index("course_code_alias_code_idx").on(t.code)],
);

/** A course as actually taught: term + section + professor. */
export const courseOffering = pgTable(
  "course_offering",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    courseId: uuid("course_id")
      .notNull()
      .references(() => course.id),
    termId: uuid("term_id")
      .notNull()
      .references(() => term.id),
    professorId: uuid("professor_id").references(() => professor.id),
    section: text("section"),
  },
  (t) => [
    uniqueIndex("course_offering_unique_idx").on(t.courseId, t.termId, t.section),
    index("course_offering_course_idx").on(t.courseId),
  ],
);

/** Packages are anchored to these. Usually transcribed by hand from a PDF syllabus. */
export const exam = pgTable(
  "exam",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    courseOfferingId: uuid("course_offering_id")
      .notNull()
      .references(() => courseOffering.id),
    name: text("name").notNull(), // "Exam 2"
    occursOn: date("occurs_on").notNull(),
  },
  (t) => [index("exam_offering_idx").on(t.courseOfferingId)],
);

export const enrollment = pgTable(
  "enrollment",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    studentProfileId: uuid("student_profile_id")
      .notNull()
      .references(() => studentProfile.id),
    courseOfferingId: uuid("course_offering_id")
      .notNull()
      .references(() => courseOffering.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("enrollment_unique_idx").on(t.studentProfileId, t.courseOfferingId),
  ],
);

/* -------------------------------------------------------------------------- */
/* supply: (tutor, course) is the core entity                                 */
/* -------------------------------------------------------------------------- */

export const tutorCourse = pgTable(
  "tutor_course",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tutorProfileId: uuid("tutor_profile_id")
      .notNull()
      .references(() => tutorProfile.id),
    /** Durable course, not the offering — history survives renumbering. */
    courseId: uuid("course_id")
      .notNull()
      .references(() => course.id),

    /** Verification: A/A- within ~4 semesters, transcript screenshot, human review. */
    gradeEarned: text("grade_earned").notNull(),
    takenTermId: uuid("taken_term_id")
      .notNull()
      .references(() => term.id),
    takenUnderProfessorId: uuid("taken_under_professor_id").references(
      () => professor.id,
    ),
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    status: tutorCourseStatus("status").notNull().default("pending_verification"),

    /**
     * Hidden quality score. Never shown to anyone.
     * At launch n=0 for everyone, so ranking is a deterministic sort; the
     * Bayesian ranker (shrinkage + bandit exploration) lands in V1.
     */
    scoreSampleCount: integer("score_sample_count").notNull().default(0),
    scorePosteriorMean: integer("score_posterior_mean"), // basis points, null until n>0

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("tutor_course_unique_idx").on(t.tutorProfileId, t.courseId),
    index("tutor_course_course_idx").on(t.courseId),
  ],
);

/* -------------------------------------------------------------------------- */
/* matching: parallel asks, first acceptance wins                             */
/* -------------------------------------------------------------------------- */

/**
 * A student may hold up to 3 `pending` requests at once. The first tutor to
 * accept wins; the rest transition to `withdrawn`. Enforce the cap and the
 * race in a transaction in the matching module, not here.
 */
export const matchRequest = pgTable(
  "match_request",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    studentProfileId: uuid("student_profile_id")
      .notNull()
      .references(() => studentProfile.id),
    tutorCourseId: uuid("tutor_course_id")
      .notNull()
      .references(() => tutorCourse.id),
    courseOfferingId: uuid("course_offering_id")
      .notNull()
      .references(() => courseOffering.id),

    status: matchRequestStatus("status").notNull().default("pending"),
    /** 12h, not 24 — a student with an exam on Thursday cannot wait a day. */
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("match_request_student_idx").on(t.studentProfileId, t.status),
    index("match_request_tutor_course_idx").on(t.tutorCourseId, t.status),
  ],
);

/* -------------------------------------------------------------------------- */
/* engagements, sessions, money                                               */
/* -------------------------------------------------------------------------- */

/** An engagement IS a course package. Many-to-many: a student takes ~4 courses. */
export const engagement = pgTable(
  "engagement",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    studentProfileId: uuid("student_profile_id")
      .notNull()
      .references(() => studentProfile.id),
    tutorCourseId: uuid("tutor_course_id")
      .notNull()
      .references(() => tutorCourse.id),
    courseOfferingId: uuid("course_offering_id")
      .notNull()
      .references(() => courseOffering.id),

    /**
     * The accepted request this package came out of. Unique, so a double
     * submit cannot buy twice; null for a renewal, which has no new request —
     * a student re-upping with a tutor they already have does not re-ask.
     */
    matchRequestId: uuid("match_request_id").references(() => matchRequest.id),

    kind: packageKind("kind").notNull().default("exam_anchored"),
    anchorExamId: uuid("anchor_exam_id").references(() => exam.id),

    sessionsPurchased: integer("sessions_purchased").notNull(),
    pricePaidMinor: integer("price_paid_minor").notNull(), // integer minor units
    currency: text("currency").notNull().default("usd"),

    /** One guaranteed first session per student per term. */
    guaranteeUsed: boolean("guarantee_used").notNull().default(false),

    status: engagementStatus("status").notNull().default("active"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    uniqueIndex("engagement_match_request_idx").on(t.matchRequestId),
    index("engagement_student_idx").on(t.studentProfileId, t.status),
    index("engagement_tutor_course_idx").on(t.tutorCourseId),
  ],
);

export const sessionBooking = pgTable(
  "session_booking",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    engagementId: uuid("engagement_id")
      .notNull()
      .references(() => engagement.id),

    scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(),
    durationMinutes: integer("duration_minutes").notNull().default(60),
    /** No video product — the pair chooses where to meet. Free text by design. */
    locationNote: text("location_note"),

    status: sessionStatus("status").notNull().default("scheduled"),

    /**
     * When a cancellation happened and who did it.
     *
     * `status` alone records that a session was cancelled but not when or by
     * whom, and that is not recoverable afterwards. The tutor-side quality
     * score is deferred to V1 by design, but the schema and the stats job ship
     * now precisely so the data has accumulated before the ranker exists — a
     * tutor's late cancel is real and does matter, and today it leaves no trace
     * at all.
     *
     * `cancelledByUserId` identifies a person, so: it is raw material for the
     * per-course stats job and nothing else. It must never become an input to
     * anything that ranks or gates on its own. The role (student or tutor) is
     * derivable by joining through the engagement, so this stores the fact and
     * leaves the interpretation to the reader.
     */
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    cancelledByUserId: text("cancelled_by_user_id").references(() => user.id),

    /** Mutual confirm. Opposed incentives — see docs/decisions.md. */
    studentConfirmedAt: timestamp("student_confirmed_at", { withTimezone: true }),
    tutorConfirmedAt: timestamp("tutor_confirmed_at", { withTimezone: true }),
    /**
     * The other half of mutual confirm: "no, it did not happen." Opposed to the
     * columns above and never set together with them.
     *
     * Recording the denial rather than flipping `status` straight to `disputed`
     * is what keeps prevention ahead of penalty: one party clicking cannot
     * freeze the session before the other has had the window to answer, and a
     * `no_showed` fact is only written once that window has actually lapsed —
     * never from a one-sided claim.
     */
    studentDeniedAt: timestamp("student_denied_at", { withTimezone: true }),
    tutorDeniedAt: timestamp("tutor_denied_at", { withTimezone: true }),
    /**
     * Free text from whoever denied, for the human resolving a contested
     * session. That is the whole of its purpose.
     *
     * It must never be read by `reliability/standing.ts`, by `matching/score.ts`,
     * or by anything else that ranks, gates or scores either side. Reliability
     * is timestamped facts only, and a free-text field is precisely the thing
     * that erodes that invariant later — one `ilike` in a ranking query and the
     * platform is quietly scoring people on someone's prose. The two
     * `*DeniedAt` timestamps above are facts and carry no such restriction.
     */
    denialNote: text("denial_note"),
    confirmationWindowEndsAt: timestamp("confirmation_window_ends_at", {
      withTimezone: true,
    }),
    resolution: attendanceResolution("resolution"),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("session_engagement_idx").on(t.engagementId),
    index("session_scheduled_idx").on(t.scheduledAt),
  ],
);

/** Append-only. Facts, never judgments. Drives mechanics, never a visible score. */
export const reliabilityEvent = pgTable(
  "reliability_event",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    sessionId: uuid("session_id").references(() => sessionBooking.id),
    type: reliabilityEventType("type").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("reliability_event_user_idx").on(t.userId, t.occurredAt)],
);

/**
 * Append-only ledger. Recognised revenue derives from here; the Stripe balance
 * is float. A package purchase is deferred revenue until sessions are delivered.
 */
export const ledgerEntry = pgTable(
  "ledger_entry",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    engagementId: uuid("engagement_id")
      .notNull()
      .references(() => engagement.id),
    sessionId: uuid("session_id").references(() => sessionBooking.id),

    type: ledgerEntryType("type").notNull(),
    amountMinor: integer("amount_minor").notNull(), // signed, integer minor units
    currency: text("currency").notNull().default("usd"),

    stripeReference: text("stripe_reference"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("ledger_entry_engagement_idx").on(t.engagementId, t.occurredAt)],
);

/* -------------------------------------------------------------------------- */
/* scheduling + demand capture                                                */
/* -------------------------------------------------------------------------- */

/**
 * Weekly recurring windows, stored as minutes from midnight in the
 * institution's timezone. A slot is picked from these *after* a tutor accepts —
 * "charge only after the tutor accepts and a slot is picked" needs somewhere for
 * the slot to come from, and asking the pair to negotiate over chat puts the
 * booking outside the ledger.
 *
 * No `institutionId`: it is reached through `tutorProfile`, which is how every
 * other child table in this schema resolves the tenant key.
 */
export const tutorAvailability = pgTable(
  "tutor_availability",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tutorProfileId: uuid("tutor_profile_id")
      .notNull()
      .references(() => tutorProfile.id),
    /** 0 = Sunday, matching `Date.prototype.getDay`. */
    weekday: integer("weekday").notNull(),
    startMinute: integer("start_minute").notNull(),
    endMinute: integer("end_minute").notNull(),
  },
  (t) => [index("tutor_availability_tutor_idx").on(t.tutorProfileId)],
);

/**
 * Supply count 0 is a real state on a fresh campus, and the decision record
 * calls for demand capture rather than an empty screen. This is the capture:
 * who wanted a tutor for which offering, and when.
 */
export const demandSignal = pgTable(
  "demand_signal",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    studentProfileId: uuid("student_profile_id")
      .notNull()
      .references(() => studentProfile.id),
    courseOfferingId: uuid("course_offering_id")
      .notNull()
      .references(() => courseOffering.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("demand_signal_unique_idx").on(t.studentProfileId, t.courseOfferingId),
  ],
);
